import type { DataTypeOption, ProcessingStepDef } from "./types"

export const PROCESSING_STEPS: ProcessingStepDef[] = [
  {
    id: "extract",
    label: "Извлечение документа",
    detail: "Структура, таблицы и координаты",
    status: "pending",
    durationMs: 0,
  },
  {
    id: "detect",
    label: "Поиск конфиденциальных данных",
    detail: "Локальные правила и выбранная LLM",
    status: "pending",
    durationMs: 0,
  },
  {
    id: "clarify",
    label: "Проверка полноты",
    detail: "Уточнение неоднозначных ролей",
    status: "pending",
    durationMs: 0,
  },
  {
    id: "redact",
    label: "Обезличивание",
    detail: "Замены с подсветкой",
    status: "pending",
    durationMs: 0,
  },
  {
    id: "report",
    label: "Формирование отчётов",
    detail: "JSON и XLSX",
    status: "pending",
    durationMs: 0,
  },
]

export const DATA_TYPE_OPTIONS: DataTypeOption[] = [
  {
    id: "person_name",
    label: "ФИО",
    description: "Имена физических лиц",
    category: "personal",
    markerPrefix: "PERSON_NAME",
    selected: true,
    color: "#3b82f6",
  },
  {
    id: "address",
    label: "Адрес",
    description: "Почтовые и юридические адреса",
    category: "personal",
    markerPrefix: "ADDRESS",
    selected: true,
    color: "#8b5cf6",
  },
  {
    id: "phone",
    label: "Телефон",
    description: "Номера телефонов",
    category: "personal",
    markerPrefix: "PHONE",
    selected: true,
    color: "#8b5cf6",
  },
  {
    id: "email",
    label: "Email",
    description: "Адреса электронной почты",
    category: "personal",
    markerPrefix: "EMAIL",
    selected: true,
    color: "#8b5cf6",
  },
  {
    id: "inn",
    label: "ИНН",
    description: "ИНН физических и юридических лиц",
    category: "financial",
    markerPrefix: "INN",
    selected: true,
    color: "#f59e0b",
  },
  {
    id: "kpp",
    label: "КПП",
    description: "КПП организации",
    category: "financial",
    markerPrefix: "KPP",
    selected: true,
    color: "#f59e0b",
  },
  {
    id: "ogrn",
    label: "ОГРН",
    description: "ОГРН и ОГРНИП",
    category: "financial",
    markerPrefix: "OGRN",
    selected: false,
    color: "#f59e0b",
  },
  {
    id: "bank_account",
    label: "Расчётный счёт",
    description: "Банковские счета",
    category: "financial",
    markerPrefix: "BANK_ACCOUNT",
    selected: true,
    color: "#f59e0b",
  },
  {
    id: "bik",
    label: "БИК",
    description: "БИК банка",
    category: "financial",
    markerPrefix: "BIK",
    selected: false,
    color: "#f59e0b",
  },
  {
    id: "amount",
    label: "Суммы",
    description: "Финансовые суммы",
    category: "financial",
    markerPrefix: "AMOUNT",
    selected: false,
    color: "#10b981",
  },
  {
    id: "contract_number",
    label: "Номер договора",
    description: "Номера договоров и контрактов",
    category: "organization",
    markerPrefix: "CONTRACT_NUMBER",
    selected: true,
    color: "#ef4444",
  },
  {
    id: "organization",
    label: "Организация",
    description: "Наименования организаций",
    category: "organization",
    markerPrefix: "ORGANIZATION",
    selected: true,
    color: "#ef4444",
  },
]
